### PR TITLE
Add Captcha to Login

### PR DESCRIPTION
**Pull request by MohammadrezaAhmadii**
This feature is used to distinguish robots from humans

refers to issue #152

### CODE REVIEW

**Comment by hamed-shirbandi** [comment]
Hi @MohammadrezaAhmadii 
Thank you very much for contributing
I need you to apply some changes to your codes:
- See how we manage service configuration in Program.cs and do the same
- See how we move common tools and configurations to Building Blocks

If you have any question, I am always glad to help 😊

**Comment by hamed-shirbandi** [comment]
Hi @MohammadrezaAhmadii 
Thank you for the changes.
There is still one thing you need to do and that is moving AddControllers() and MapEndPoints() from CaptchConfiguration to Identity.Api Configuartion. because they are not belong to Captcha configs.

**Comment by MohammadrezaAhmadii** [comment]
Hi Hamed
Thankes, I do it.

**Comment by hamed-shirbandi** [comment]
Welcome to TaskoMask!

**Pull request merged**
